require:
  - rubocop-performance

AllCops:
  UseCache: true
  CacheRootDirectory: './tmp/cache'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Exclude:
    - ./attr-gather.gemspec
    - ./bin/**/*
    - ./examples/**/*

Naming/FileName:
  Exclude:
    - ./lib/attr-gather.rb

Style/Documentation:
  Exclude:
    - ./examples/**/*
    - ./spec/**/*

Metrics/CyclomaticComplexity:
  Exclude:
    - ./lib/attr/gather/workflow/dsl.rb

Metrics/PerceivedComplexity:
  Exclude:
    - ./lib/attr/gather/workflow/dsl.rb
