---
name: Doc
on: [push]
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build
        run: bundle exec yard
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: github.ref == 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: doc # The folder the action should deploy.
