---
name: Doc
on: [push]
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build
        run: |
          gem install bundler
          bundle install --without=local --jobs 4 --retry 3
          bundle exec yard
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@master
        if: github.ref == 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: doc # The folder the action should deploy.
