---
name: Build + Test + Lint
on: [push]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1"]
    steps: 
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Deps
        run: bundle install --jobs 4 --retry 3
      - name: Test
        run: bundle exec rake spec
      - name: Lint
        run: bundle exec rake lint
