---
name: Build + Test + Lint
on: [push]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.4.x", "2.5.x", "2.6.x", "2.7.x"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build
        run: |
          gem install bundler
          bundle install --without=local --jobs 4 --retry 3
      - name: Test
        run: bundle exec rake spec
      - name: Lint
        run: bundle exec rake lint
